name: Use the data

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' }}
    steps:
      - name: 'Download Artifact'
        uses: actions/download-artifact@v3
        with:
          name: coverage-report

      - name: 'Comment on PR'
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: lcov.info
          delete-old-comments: true
